using STB.Client.Audio.Internal;

namespace STB.Client.Audio
{
    public enum eCommonAction : uint
    {
        Death = AK.SWITCHES.HITTABLE_ELEMENT.SWITCH.DEATH,
        Hit = AK.SWITCHES.HITTABLE_ELEMENT.SWITCH.HIT,
        Respawn = AK.SWITCHES.HITTABLE_ELEMENT.SWITCH.RESPAWN,
        
        Walk = AK.SWITCHES.MOVABLE_ELEMENT.SWITCH.WALK,
        Run = AK.SWITCHES.MOVABLE_ELEMENT.SWITCH.RUN,
        Stop = AK.SWITCHES.MOVABLE_ELEMENT.SWITCH.STOP,
        Charge = AK.SWITCHES.MOVABLE_ELEMENT.SWITCH.CHARGE,

        Active = AK.SWITCHES.BASE_CHARACTER.SWITCH.ACTIVE,
        Passive = AK.SWITCHES.BASE_CHARACTER.SWITCH.PASSIVE,
        Ulti = AK.SWITCHES.BASE_CHARACTER.SWITCH.ULTI,

        PassiveStart = AK.SWITCHES.BASE_CHARACTER.SWITCH.PASSIVE_START,
        PassiveEnd = AK.SWITCHES.BASE_CHARACTER.SWITCH.PASSIVE_END,

        ActiveStart = AK.SWITCHES.BASE_CHARACTER.SWITCH.ACTIVE_START,
        ActiveEnd = AK.SWITCHES.BASE_CHARACTER.SWITCH.ACTIVE_END,

        UltiStart = AK.SWITCHES.BASE_CHARACTER.SWITCH.ULTI_START,
        UltiEnd = AK.SWITCHES.BASE_CHARACTER.SWITCH.ULTI_END
    }
}